const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

const DEFAULT_SITE_ID = process.env.DEFAULT_SITE_ID || '11111111-1111-1111-1111-111111111111';

async function main() {
  await prisma.site.upsert({
    where: { id: DEFAULT_SITE_ID },
    update: {
      name: 'Default Site',
      code: 'DEFAULT',
      updated_at: new Date(),
    },
    create: {
      id: DEFAULT_SITE_ID,
      name: 'Default Site',
      code: 'DEFAULT',
      address: 'Autogenerated default site',
    },
  });

  const announcements = [
    {
      id: '11111111-1111-1111-1111-111111111111',
      site_id: DEFAULT_SITE_ID,
      title: 'Mandatory Safety Training',
      message: 'Attend the safety briefing at the site office today at 2:00 PM. Please be on time and bring your safety gear.',
      priority: 'high',
      expiry_date: new Date(new Date().setDate(new Date().getDate() + 1)),
    },
    {
      id: '22222222-2222-2222-2222-222222222222',
      site_id: DEFAULT_SITE_ID,
      title: 'Equipment Maintenance',
      message: 'The north crane will undergo maintenance tomorrow between 9:00 AM and 12:00 PM. Expect delays near zone B.',
      priority: 'medium',
      expiry_date: new Date(new Date().setDate(new Date().getDate() + 3)),
    },
    {
      id: '33333333-3333-3333-3333-333333333333',
      site_id: DEFAULT_SITE_ID,
      title: 'Holiday Notice',
      message: 'Site operations will be closed on Sunday for scheduled power maintenance. Regular work resumes Monday 8:00 AM.',
      priority: 'low',
      expiry_date: new Date(new Date().setDate(new Date().getDate() + 7)),
    },
  ];

  for (const announcement of announcements) {
    await prisma.announcement.upsert({
      where: { id: announcement.id },
      update: {
        title: announcement.title,
        message: announcement.message,
        priority: announcement.priority,
        expiry_date: announcement.expiry_date,
        is_active: true,
        site_id: announcement.site_id,
      },
      create: announcement,
    });
  }
}

main()
  .catch((e) => {
    console.error('Failed to seed default site', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });

